name: CI

on:
  push:
    branches:
      - '*'
      - '!main'

env:
  RUN: ${{ github.run_id }}-${{ github.run_number }}
  PACKAGE_NAME: aws-iot-device-sdk-js
  AWS_EC2_METADATA_DISABLED: true
  CRT_CI_ROLE: ${{ secrets.CRT_CI_ROLE_ARN }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Unit Tests - Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x]
        test-type: [websocket, certificate, custom-auth]

    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.test-type }} Integration Tests - Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.CRT_CI_ROLE }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - run: cd integration-testing && ./run-tests.sh ${{ matrix.test-type }}
